---
baseurl: "http://backgroundprocess.com/"
title: "Background Process"
languageCode: "en-us"
params:
  description: "This site hosts my mental Background Process output."
metaDataFormat: "yaml"
#theme: nofancy
